merge:
  client: 5174
  server: 3000
  port: 8081

processes:
  client:
    cmd: npm run dev
    dir: ./multysis-frontend
    env:
      PORT: "5174"
  server:
    cmd: npm run dev
    dir: ./multysis-backend
    env:
      PORT: "3000"
    restart: on-failure
